generic-service:
  nameOverride: hmpps-prisoner-pay-api
  productId: "DPS028" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-prisoner-pay-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: prisoner-pay-api-cert
    path: /
    annotations:
      # Secure the endpoints related to k8s jobs from outside the Kubernetes ingress
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
        location /job-admin/run/{jobName} {
          deny all;
          return 401;
        }
        location /utility/ {
          deny all;
          return 401;
        }

  # Used to access resources like SQS queues and SNS topics
  serviceAccountName: hmpps-prisoner-pay

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-prisoner-pay-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-prisoner-pay-api-client-creds:
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
    prisoner-pay-rds:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    sqs-prisoner-pay-api-jobs-queue-secret:
      HMPPS_SQS_QUEUES_PRISONERPAYJOBS_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-pay-api-jobs-dlq-secret:
      HMPPS_SQS_QUEUES_PRISONERPAYJOBS_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-prisoner-pay-api

cron:
  makePayments: "0 2 * * *"
