version: "3"

services:
  test-db:
    image: postgres:18
    networks:
      - hmpps
    container_name: prisoner-pay-api-test-db
    restart: always
    ports:
      - "15444:5432"
    environment:
      POSTGRES_DB: prisoner-pay
      POSTGRES_USER: prisoner-pay
      POSTGRES_PASSWORD: prisoner-pay

networks:
  hmpps:
