---
# Per environment values which override defaults in hmpps-prisoner-pay-api/values.yaml

generic-service:
  ingress:
    host: prisoner-pay-api.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_HMPPS_AUTH: "https://sign-in.hmpps.service.justice.gov.uk/auth"

  namespace_secrets:
    sqs-prisoner-pay-api-jobs-queue-secret:
      HMPPS_SQS_QUEUES_PRISONERPAYJOBS_QUEUE_NAME: "sqs_queue_name"
    sqs-prisoner-pay-api-jobs-dlq-secret:
      HMPPS_SQS_QUEUES_PRISONERPAYJOBS_DLQ_NAME: "sqs_queue_name"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-activities-management-prod
